<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net8.0\test7.txt" />
    <Content Include="bin\Debug\net8.0\test7utf8.txt" />
    <Content Include="bin\Debug\net8.0\test7utfhm.txt" />
  </ItemGroup>

</Project>
